config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, path: '/'
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions' }
  resources :pantry_items

  namespace :admins do
    get '/', to: 'home#index'
    resources :categories do
      resources :products, only: %i[create update edit new destroy]
    end
  end
end

app/models/admin.rb
# frozen_string_literal: true

class Admin < ApplicationRecord
  devise :database_authenticatable
  validates :email, presence: true, uniqueness: true, format: { with: /\A.+@.+\..+\z/, message: 'has incorrect format' }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/pantry_item.rb
# frozen_string_literal: true

class PantryItem < ApplicationRecord
  belongs_to :product

  validates :name, presence: true
  validates :quantity, presence: true
  validates :measurement, presence: true
  validates :expire_date, presence: true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  has_many :pantry_items

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable
  validates :email, presence: true, uniqueness: true, format: { with: /\d.+@.+\..+\z/, message: 'has incorrect format' }
  validates :username, presence: true, uniqueness: true
end

app/controllers/admins/base_controller.rb
# frozen_string_literal: true

module Admins
  class BaseController < ApplicationController
    before_action :authenticate_admin!
  end
end

app/controllers/admins/categories_controller.rb
# frozen_string_literal: true

module Admins
  class CategoriesController < BaseController
    include Pagy::Backend
    before_action :set_category, only: %i[show edit update destroy]
    def show
      @pagy, @products = pagy(Product.where(category_id: params[:id]))
    end

    def index
      @pagy, @categories = pagy(Category.all, items: 10)
    end

    def new
      @category = Category.new
    end

    def edit; end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admins_categories_path, notice: 'Category successfully created!'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @category.update(category_params)
        redirect_to admins_categories_path, notice: 'Category successfully edited!'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @category.destroy
      redirect_to admins_categories_path, notice: 'Category successfully deleted!'
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/admins/home_controller.rb
# frozen_string_literal: true

module Admins
  class HomeController < Admins::BaseController
    def index; end
  end
end

app/controllers/admins/products_controller.rb
# frozen_string_literal: true

module Admins
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[edit update destroy]
    before_action :set_category, only: %i[edit new update create]

    def new
      @product = Product.new
    end

    def edit; end

    def create
      @product = Product.new(product_params.merge(category_id: params[:category_id]))
      if @product.save
        redirect_to admins_category_path(category_id), notice: 'Product successfully added!'
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @product.update(product_params)
        redirect_to admins_category_path(category_id), notice: 'Product successfully edited!'
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @product.destroy
      redirect_to admins_category_path(category_id), notice: 'Product successfully deleted!'
    end

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name)
    end

    def category_id
      @category_id ||= params[:category_id].to_i
    end

    def set_category
      @category = Category.find(category_id)
    end
  end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

module Admins
  class SessionsController < Devise::SessionsController
    def after_sign_in_path_for(_)
      admins_path
    end

    def after_sign_out_path_for(_)
      new_admin_session_path
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/base_controller.rb
# frozen_string_literal: true

class BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ::BaseController
  def index; end
end

app/controllers/pantry_items_controller.rb
# frozen_string_literal: true

class PantryItemsController < ApplicationController
  before_action :set_pantry_item, only: %i[show edit update destroy]
  before_action :set_products_for_select, only: %i[new edit]

  def show; end

  def index
    @pantry_items = PantryItem.all
  end

  def new
    @pantry_item = PantryItem.new
  end

  def edit; end

  def create
    @pantry_item = PantryItem.new(pantry_item_params)
    if @pantry_item.save
      redirect_to pantry_items_path, notice: 'Pantry Item successfully created!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @pantry_item.update(pantry_item_params)
      redirect_to pantry_items_path, notice: 'Pantry Item successfully edited!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pantry_item.destroy
    redirect_to pantry_items_path, notice: 'Pantry Item successfully deleted!'
  end

  private

  def pantry_item_params
    params.require(:pantry_item).permit(:product_id, :name, :quantity, :measurement, :expire_date)
  end

  def set_pantry_item
    @pantry_item = PantryItem.find(params[:id])
  end

  def set_products_for_select
    @products_for_select = Product.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# top-level documentation
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
  include Pagy::Frontend
end

app/views/admins/categories/_form.html.erb
<%= render 'admins/shared/validation_errors', record: @category %>

<%= form_with(model: [ :admins, @category ]) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit 'Save' %>
  </p>

<% end %>

app/views/admins/categories/edit.html.erb
  <h1>Edit category</h1>

  <%= render 'form' %>

  <%= link_to 'Back to the list of categories', admins_categories_path %>

app/views/admins/categories/index.html.erb
<%= link_to 'Back to admin panel', admins_path %>
<h1>Categories</h1>
<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, admins_category_path(category) %></li>
  <% end %>
</ul>
<%== pagy_nav(@pagy) %> <br>
<%= link_to 'Add new category', new_admins_category_path %>

app/views/admins/categories/new.html.erb
  <h1>Add new category</h1>

  <%= render 'form' %>

  <%= link_to 'Back to list of categories', admins_categories_path %>

app/views/admins/categories/show.html.erb
<%= link_to 'Back to the list of categories', admins_categories_path %>
<h1><%= @category.name %></h1>

<ul>
  <% @products.each do |product| %>
    <li class="product-item">
      <div><%= product.name %></div>
      <div><%= link_to 'Edit',edit_admins_category_product_path(@category, product) %></div>
      <div><%= link_to 'Delete', admins_category_product_path(@category, product), data: { 'turbo-method': :delete, 'turbo-confirm': 'Are You sure?' } %></div>
    </li>
  <% end %>
  <%== pagy_nav(@pagy) %>
</ul>
<%= link_to 'Add new product', new_admins_category_product_path(@category.id) %><br>
<br>
<%= link_to 'Edit category', edit_admins_category_path %> |
<%= link_to 'Delete category', admins_category_path(@category), data: { 'turbo-method': :delete, 'turbo-confirm': 'Are You sure?' } %>

app/views/admins/home/index.html.erb
<nav>
  <%= link_to :logout, destroy_admin_session_path, data: { 'turbo-method': :delete } %> |
  <%= link_to :categories, admins_categories_path %>
</nav>
<h1>Admin Panel</h1>

app/views/admins/products/_form.html.erb
<%= render 'admins/shared/validation_errors', record: @product %>

<%= form_with(model: [ :admins, @category, @product ]) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit 'Save' %>
  </p>

<% end %>

app/views/admins/products/edit.html.erb
  <h1>Edit product</h1>

  <%= render 'form' %>

  <%= link_to 'Back to the list of products', admins_categories_path %>

app/views/admins/products/new.html.erb
<h1>Add new product</h1>

<%= render 'form' %>

<%= link_to 'Back to category', admins_categories_path %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/admins/shared/_validation_errors.html.erb
<% if record.errors.any? %>
  <p>Prohibited this category from being saved:</p>
  <ul>
    <% record.errors.each do |msg| %>
      <li><%= msg.full_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/home/index.html.erb
<%= link_to 'Your pantry items', pantry_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodPantryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pantry_items/_form.html.erb
<%= form_with(model: [@pantry_item]) do |f| %>
  <p>
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :quantity %><br/>
    <%= f.number_field :quantity %>
  </p>
  <p>
    <%= f.label :measurement %><br/>
    <%= f.text_field :measurement %>
  </p>
  <p>
    <%= f.label :expire_date, 'Expire Date' %><br/>
    <%= f.date_field :expire_date %>
  </p>
  <p>
    <%= f.label :product_id, 'Select Product' %><br/>
    <%= f.select :product_id, Product.all.collect { |product| [product.name, product.id] }, {}, class: 'product' %>
  </p>

  <p>
    <%= f.submit 'Save' %>
  </p>

<% end %>

app/views/pantry_items/edit.html.erb
<h1>Edit Pantry Item</h1>

<%= render 'pantry_items/form' %>

<%= link_to 'Back to the list of Pantry Items', pantry_items_path %>

app/views/pantry_items/index.html.erb
<%= link_to 'Back to home', root_path %>
<h1>Your Pantry Items</h1>

<ul>
  <% @pantry_items.each do |pantry_item| %>
  <li>
    <%= pantry_item.name %> | <%= "#{pantry_item.quantity} #{pantry_item.measurement}" %> | <%= pantry_item.expire_date %> |
    <%= link_to 'Edit', edit_pantry_item_path(pantry_item) %> |
    <%= link_to 'Delete', pantry_item_path(pantry_item), data: { 'turbo-method': :delete, 'turbo-confirm': 'Are You sure?' }%>
  </li>
  <% end %>
</ul>

<%= link_to 'Add new pantry item', new_pantry_item_path %>

app/views/pantry_items/new.html.erb
<h1>Add new Pantry Item</h1>

<%= render 'pantry_items/form' %>

<%= link_to 'Back to the list of Pantry Items', pantry_items_path %>